inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/migrate/**/*.rb
    - node_modules/**/*

Style/IndentationWidth:
  Severity: warning

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
